server:
  port: 1060

spring:
  application:
    name: security-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1010/eureka
  instance:
    hostname: localhost

services:
  userUrl: http://localhost:1040/user/